### ISSUE TITLE
Question: How are multiple @Embeddable entity columns distinguished?

### ISSUE THREAD

**Issue by vnayar** [buggins/hibernated#79] opened 2023-10-18 11:02 UTC
Consider the following case:
```
    // for testing of Embeddable
    @Embeddable 
    class EMName {
        string firstName;
        string lastName;
    }
    
    //@Entity 
    class EMUser {
        //@Id @Generated
        //@Column
        int id;
        
        // deduced as @Embedded automatically
        EMName userName;

        // deduced as @Embedded automatically
        EMName aliasName;
    }
```

In this case, an error like the following will appear:
```
hibernated.type.HibernatedException@../../src/hibernated/source/hibernated/metadata.d(3727): duplicate column name em_user.first_name in schema
```

In Java hibernate, the attribute `@AttributeOverride` is used to resolve such ambiguities.
https://docs.jboss.org/hibernate/jpa/2.1/api/javax/persistence/AttributeOverride.html

What is the recommended approach to take using HibernateD?

**Comment by vnayar** [comment] 2023-10-18 11:05
I don't know if it would violate the Hibernate standard, but what if a prefix could be added by specifying the column name for an embedded object?

For example:
```
    //@Entity 
    class EMUser {
        //@Id @Generated
        //@Column
        int id;
        
        // deduced as @Embedded automatically
        @Embedded("user")    // Produces columns: user_first_name, user_last_name
        EMName userName;

        // deduced as @Embedded automatically
        @Embedded("alias")  // Produces columns: alias_first_name, alias_last_name
        EMName aliasName;
    }
```

**Comment by SingingBush** [comment] 2023-10-19 14:20
Hibernated doesn't have feature parity with Hibernate but that should be the goal. I don't think I've used x2 embedded objects with Hibernated and suspect it may not currently work. That said, it would be nice if the default behaviour, even without having `@AttributeOverrides`, did something sensible like this

```
@Embeddable
class Address {
    string line1;
    string line2;
    string line3;
    string line4;
    string zipcode;
}

// current behaviour:
Address address; // will look for line1, etc

// new behaviour when dealing with multiple embedded:
Address billing; // will look for billingLine1 or billing_line1, etc

Address shipping; // will look for shippingLine1 or shipping_line1, etc
```

**Comment by vnayar** [comment] 2023-10-19 14:43
Personally I would be very happy with such default behavior. But at the same time, I don't know if other people's existing code would break upon changing things. One advantage of creating an `@Embedded` tag is that, because it's an optional flag and the fact that things are embedded is already detectable, no existing code would break.

However, your suggestion has a strong argument in that it does not technically violate JPA or Hibernate standards, in which I can find no locked-down definition of what the column names should be. They only reference a "PhysicalNamingStrategy", but it's not specific. https://docs.jboss.org/hibernate/orm/6.3/userguide/html_single/Hibernate_User_Guide.html#naming

The official hibernate interface uses multiple attributes like the following:
```
@Entity
@CompositeTypeRegistration( embeddableClass = Name.class, userType = NameCompositeUserType.class )
public class Person {
	@Id
	public Integer id;

	@Embedded
	@AttributeOverride(name = "firstName", column = @Column(name = "first_name"))
	@AttributeOverride(name = "lastName", column = @Column(name = "last_name"))
	public Name name;
```

Technically it works, although I'm not the biggest fan of how verbose this syntax is. It requires you to go to every single attribute and make an `@AttributeOveride`, and it's just a lot of repetition of code. If one attribute is changed or added, then every single location where it is used must be modified as well.

Hibernate has this because, in addition to it's own API, it also implements JPA, and JPA is where it comes from: https://www.objectdb.com/api/java/jpa/Embedded

According to the JPA standard, `@Embedded` has no parameters, which to me just seems like a wasted opportunity.

**Comment by SingingBush** [comment] 2023-10-19 15:44
I'm not an advocate of being cavalier around potentially breaking changes but it is worth remembering that HibernateD, like many D projects, is not widely used. So far there are only 9 downloads this month. Plus it's still released as version 0.* so it's reasonable for users to expect API changes occasionally. 

For a small project like this it's probably best to say that the developer implementing the feature gets to choose how it works. :smiley:

HibernateD should feel familiar to users that have used Hibernate before. It doesn't need to be an exact match, just close enough for users to be productive. With that in mind, I'm open to it not being as verbose as Hibernate is in this scenario.

I'm happy to merge a PR for this as long as 

 - the code has test coverage to prove that it works as intended. 
 - the feature is documented
 - it can be seen either in the existing example project or in a new example project (eg; examples/example2)

I suggest using `Address billing;` and `Address shipping;` for the documentation/example as it's a very common use case.

**Comment by vnayar** [comment] 2023-11-11 16:16
Greetings. I've been spending quite a bit of time to comprehend the way the code works, especially in `metadata.d`. Thus far, I've been unable to find a mechanism to carry information about an embedded property into the property itself.

For example:
```
@Entity
class MyEntity {
  @Embedded
  Thing t1;
}

class Thing {
  int a; int b;
}
```

It seems that when the `PropertyInfo` values are being computed, there is no context retained about the path that led there.  E.g. when property `a` of `Thing` is being processed, there's no awareness of it being a particular instance of `Thing` named `t1`.

I'm struggling to find a place to fit this in, partially because the code generation happens roughly at the same time properties are discovered. Consider:

```
/**
 * Given a class T, generate D code as a string that defines an `EntityInfo` object that describes
 * the class.
 */
string getEntityDef(T)() {
  ...
      foreach (m; __traits(allMembers, T)) {
        //pragma(msg, m);

        static if (__traits(compiles, (typeof(__traits(getMember, T, m))))){

            // skip non-public members
            static if (__traits(getProtection, __traits(getMember, T, m)) == "public") {
                ...
                // When this method is called, EntityInfo does not yet exist, the string is still being generated.
                immutable string propertyDef = getPropertyDef!(T, m)();
```

I have a feeling that I'm barking up the wrong tree to find a place to implement the ability to either refer to the name of the containing `@Embeddable` property. Do you have any suggestions on what the best direction to approach this problem would be?

**Comment by SingingBush** [comment] 2023-11-15 11:34
I've not dug around in the code significantly for quite a while. It looks like you're in the right place to dig in though. The *m* string should be what you are referring to I believe. In your example that should be `t1` and then when it the code goes in to _getPropertyDef_ the _isEmbedded_ property should be added:
 https://github.com/buggins/hibernated/blob/c0720968ad682d16f25775c5496bd769c15504aa/source/hibernated/metadata.d#L2946-L2955

**Comment by SingingBush** [comment] 2023-11-23 20:13
Thanks for your work on this. I've taken a quick look at the PR and it all seems fine. I'm on a mobile phone at the minute so would like to take another look when back home before clicking merge. Once merged I'll tag a new release.

**Comment by vnayar** [comment] 2023-11-23 20:26
Of course, I appreciate the time you've invested to review. Going through the code, I certainly respect much more of a monumental task this was to produce. I'm also glad to hear that the changes are at least in the right direction and don't have to be fundamentally rethought (I had a few missteps like that already).

One area I am not currently satisfied within my code is how the tests are all starting to clump up into a pile. I'm currently working on a mechanism to make tests easier to run in small specialized parts without having to write all the database connection setup for each test. That part will probably be added to the PR tomorrow, or it can be a separate follow-up PR too, either way.

**Comment by vnayar** [comment] 2023-11-23 22:39
While beefing up the tests, I found an error I'll have to resolve before this can move on. Apparently embedded properties that have a prefix are not being found when doing FROM ... WHERE hibernate query. I must have missed a spot where property => column conversions happen.

**Comment by SingingBush** [comment] 2023-11-24 11:53
ok thanks for letting me know. I'm looking through it now. looks like those tests with `todo` in them should be part of the PR and perhaps that _DoomyTest_ was some example code that was not meant to be included.

**Comment by vnayar** [comment] 2023-11-24 19:02
Ah, the DoomyTest thingy is basically a test for the test runner itself, to make sure it pulls out methods annotated with `@Test`, `@BeforeClass`, and `@AfterClass`, and runs them in the right order.  I'm hoping the remaining changes needed are fast to diagnose, I feel I'm getting a better understanding of the source code the more time I spend on it.

**Comment by vnayar** [comment] 2023-11-26 10:04
The last bugs are fixed, it should be good to review.

One open question I have is, I noticed that `.editorconfig` files have been recently added. But I also noticed that the existing files don't quite follow the settings followed in the file. I can use `dfmt` to apply the settings to certain files, but the question is, which files should I apply it to?

I figured you may want to personally play around with tweaking `.editorconfig` and see which style you like before finally committing to one. Personally I like the Google Java and C++ styles due to their relative lack of ambiguity, and use tools that help with that.

**Closed** 2023-11-26 11:29 UTC
Labels: enhancement

**Comment by SingingBush** [comment] 2023-11-26 11:53
Merged as is, formatting can get sorted out another time. I don't think lines should be limited to 80 chars and tend to stick to 4 spaces indentation, except for yml.
